num1 = input('Enter 1st number : ')
num2 = input('Enter 2st number : ')
print(num1,'+',num2,'=',float(num1)+float(num2))
print(num1,'-',num2,'=',float(num1)-float(num2))
print(num1,'*',num2,'=',float(num1)*float(num2))
print(num1,'/',num2,'=',float(num1)/float(num2))